name: poshan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.66.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  http: ^1.2.1
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.13.1   # ✅ CORRECT PLACE

flutter_icons:                      # ✅ TOP-LEVEL
  android: true
  ios: false
  image_path: "assets/icon/grass.png"

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/icon/grass.png          # ✅ ADD THIS
